add dotenv-linter and dotenv_if_exists to direnv

diff --git a/.config/direnv/direnvrc b/.config/direnv/direnvrc
--- a/.config/direnv/direnvrc
+++ b/.config/direnv/direnvrc
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+if [[ -f .env ]] && command dotenv-linter --version >&/dev/null; then
+        dotenv-linter .env || echo 'ERROR|https://dotenv-linter.github.io'
+fi
+
+dotenv_if_exists || direnv status # https://direnv.net/man/direnv-stdlib.1.html
+
 # use a certain pyenv version
 use_python() {
         if [ -n "$(which pyenv)" ]; then
